laber: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-sell?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
    jpa:
      show-sql: true
  application:
    name: order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8801
env: 
  dev